//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace InjectSourceGen
{
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (Equals(null, resourceMan))
                {
                    ResourceManager temp = new ResourceManager("InjectSourceGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string AB0001Description
        {
            get { return ResourceManager.GetString("AB0001Description", resourceCulture); }
        }

        internal static string AB0001MessageFormat
        {
            get { return ResourceManager.GetString("AB0001MessageFormat", resourceCulture); }
        }

        internal static string AB0001Title
        {
            get { return ResourceManager.GetString("AB0001Title", resourceCulture); }
        }

        internal static string AB0001CodeFixTitle
        {
            get { return ResourceManager.GetString("AB0001CodeFixTitle", resourceCulture); }
        }

        internal static string AB0002Description
        {
            get { return ResourceManager.GetString("AB0002Description", resourceCulture); }
        }

        internal static string AB0002MessageFormat
        {
            get { return ResourceManager.GetString("AB0002MessageFormat", resourceCulture); }
        }

        internal static string AB0002Title
        {
            get { return ResourceManager.GetString("AB0002Title", resourceCulture); }
        }
    }
}